config/routes.rb
Rails.application.routes.draw do
  
  resources :blogs do
    resources :entries, except: 'index'
  end

  resources :entries, only:'' do
    resources :comments, only: ['create', 'destroy']
  end
  
  resources :comments, only: 'approve' do
    member do
      get 'approve'
    end
  end
  

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :entries

  validates :title, presence: true

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :entry
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :blog
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end

  def show
    @entries = @blog.entries
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
#       @blog = Blog.where("id = #{params[:id]}").first # security test
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  def create
    @entry = Entry.find(params[:entry_id])
    @comment = Comment.new(comment_params)
    @blog = Blog.find(@entry.blog_id)
    
    respond_to do |format|
      if @comment.save
        format.html { 
          redirect_to blog_entry_path(@entry.blog_id, @entry.id), notice: 'Comment was successfully created.' 
          send_mail @blog, @entry, @comment
          }
      else
        format.html { redirect_to blog_entry_path(@entry), error: 'Comment was not successfully created.'  }
      end
    end
  end

  def send_mail(blog, entry, comment)
#     user = User.find(1)

    @mail = NoticeMailer.sendmail_confirm(blog, entry, comment).deliver
#     render :text => "送信できた！"
  end
  
  def approve
    respond_to do |format|
      @comment = Comment.find(params[:id])
      @comment.status = 'approved'
      @entry = Entry.find(@comment.entry_id)
      if @comment.save()
        format.html { redirect_to blog_entry_path(@entry.blog_id, @entry.id), notice: 'Comment was successfully approved.' }
      else
        format.html { redirect_to blog_entry_path(@entry.blog_id, @entry.id), notice: 'Comment was not successfully approved.' }
      end
    end
  end

  def destroy
    @entry = Entry.find(@comment.entry_id)
    @blog = Blog.find(@entry.blog_id)
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to blog_entry_path(@blog, @entry), notice: 'Comment was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:entry_id, :body, :status)
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  before_filter :load_blog

  def index
    @entries = @blog.entries
  end

  def show
    @comments = @entry.comments
    @comment =  Comment.new # @entry.comments.build
  end

  def new
    @entry = @blog.entries.build
  end

  def edit
  end

  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to [@blog, @entry], notice: 'Entry was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to [@blog, @entry], notice: 'Entry was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
    end
  end

  def load_blog
    @blog = Blog.find(params[:blog_id])
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
      #       @entry = Entry.where("id = #{params[:id]}").first #security test
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:blog_id, :title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit 'save', class: 'btn btn-default active' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Listing blogs</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<% if notice %>
<p id="notice" class="alert alert-info"><%= notice %></p>
<% end %>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

<hr>

<%= render 'layouts/entries' %>

app/views/entries/_form.html.erb
<%= form_for([@blog, @entry]) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    
  <%= f.hidden_field :blog_id %>
  
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit 'save', class: 'btn btn-default active' %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', blog_entry_path(@blog.id, @entry.id) %> |
<%= link_to 'Back', blog_path(@blog) %>

app/views/entries/index.html.erb
<%= render 'layouts/entries' %>
<%= link_to 'Back', blog_entries_path(@blog) %>

app/views/entries/new.html.erb
<h1>New entry：<%= @blog.title %></h1>

<%= render 'form' %>

<%= link_to 'Back', blog_entries_path(@blog) %>

app/views/entries/show.html.erb
<% if notice %>
<p id="notice" class="alert alert-info"><%= notice %></p>
<% end %>

<p>
  <strong>Title:</strong>
  <%= @entry.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @entry.body %>
</p>

<%= link_to 'Edit', edit_blog_entry_path(@blog.id, @entry.id) %> |
<%= link_to 'Back', blog_path(@blog) %>

<hr>

<h1>Listing comments</h1>

<table class="table">
  <thead>
    <tr>
      <th>Body</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <% if comment.status == 'approved' %>
        <td><%= comment.body %></td>
        <td></td>
        <% else %>
        <td>（承認待ち）</td>
        <td><%= link_to 'Approve', approve_comment_path(comment.id), data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        
        <td><%= link_to 'Destroy', [@entry, comment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>New comment</h1>
<%= form_for([@entry, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: 'form-control' %>
    <%= f.hidden_field :entry_id, value: @entry.id %>
  </div>
  <div class="actions">
    <%= f.submit 'save', class: 'btn btn-default active' %>
  </div>
<% end %>

app/views/layouts/_entries.html.erb
<h1>Listing entries</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.title %></td>
        <td><%= entry.body %></td>
        <td><%= link_to 'Show',      blog_entry_path(@blog.id, entry.id) %></td>
        <td><%= link_to 'Edit', edit_blog_entry_path(@blog.id, entry.id) %></td>
        <td><%= link_to 'Destroy', [@blog, entry], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_blog_entry_path(@blog) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogPlactice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
  <%= yield %>
  </div>
</body>
</html>